### PR TITLE
Check whether alpha information is present- then drop it (with a warning).

### LINKED ISSUE #4: colourInput fails if color passed to 'value' contains alpha.
This throws an error:

```
library(shiny)
library(colourpicker)
shinyApp(
  ui = fluidPage(
    strong("Selected colour:", textOutput("value", inline = TRUE)),
    colourInput("col", "Choose colour", "#FF0000FF"),
    h3("Update colour input"),
    textInput("text", "New colour: (colour name or HEX value)"),
    selectInput("showColour", "Show colour",
                c("both", "text", "background")),
    selectInput("palette", "Colour palette",
                c("square", "limited")),
    checkboxInput("allowTransparent", "Allow transparent", FALSE),
    checkboxInput("returnName", "Return R colour name", FALSE),
    actionButton("btn", "Update")
  ),
  server = function(input, output, session) {
    observeEvent(input$btn, {
      updateColourInput(session, "col",
                        value = input$text, showColour = input$showColour,
                        allowTransparent = input$allowTransparent,
                        palette = input$palette,
                        returnName = input$returnName)
    })
    output$value <- renderText(input$col)
  }
)

Error: #FF0000FF is not a valid colour
```
Not sure if possible/easy to add ability to set alpha. Alternatively, could drop alpha information instead of error? Function viridis() returns colors this way. Of course I can remove the information myself but wondering whether it would be better handled directly here.

### PR DESCRIPTION
**Pull request by ddiez**
This tries to fix [#4](https://github.com/daattali/colourpicker/issues/4). Basically I let 8 digit colors pass as valid, then checks and drops the last two digits with a warning.

### CODE REVIEW

**Review by daattali — COMMENTED** [review]
Thanks,  I'll take a look within 48 hours just to give you an ETA

File: R/colourInput.R [hunk 1]
```diff
@@ -221,10 +221,16 @@ formatHEXsingle <- function(x) {
...
   }
-  if (!grepl("^#?([[:xdigit:]]{3}|[[:xdigit:]]{6})$", x)) {
+  if (!grepl("^#?([[:xdigit:]]{3}|[[:xdigit:]]{6}|[[:xdigit:]]{8})$", x)) {
     stop(sprintf("%s is not a valid colour", x), call. = FALSE)
   }
 
+  # check whether it is 6-digit hex code with alpha.
+  if (substr(x, 1, 1) == "#" && nchar(x) == 9) {
+    x <- substr(x, 1, 7)
+    warning("colourpicker does not support colours with transparency. Alpha channel information dropped.")
```
Comment (daattali) [inline R/colourInput.R]: Could you add `call. = FALSE` to the `warning()` call, so that it will print out much nicer?

File: R/colourInput.R [hunk 2]
```diff
@@ -221,10 +221,16 @@ formatHEXsingle <- function(x) {
   if (x %in% grDevices::colors()) {
     x <- do.call(grDevices::rgb, as.list(grDevices::col2rgb(x) / 255))
   }
-  if (!grepl("^#?([[:xdigit:]]{3}|[[:xdigit:]]{6})$", x)) {
+  if (!grepl("^#?([[:xdigit:]]{3}|[[:xdigit:]]{6}|[[:xdigit:]]{8})$", x)) {
     stop(sprintf("%s is not a valid colour", x), call. = FALSE)
   }
 
+  # check whether it is 6-digit hex code with alpha.
```
Comment (daattali) [inline R/colourInput.R:233]: I think this if statement should move a few lines down, because the next if statement makes sure to add a # to the beginning. Then passing in a HEX colour with alpha without the pound symbol will work

File: R/colourInput.R [hunk 3]
```diff
@@ -221,10 +221,16 @@ formatHEXsingle <- function(x) {
...
+  if (substr(x, 1, 1) == "#" && nchar(x) == 9) {
```
Comment (daattali) [inline R/colourInput.R]: I'm not too familiar with RGB specification with alpha: is a 4/5-digit specification not allowed? For example "#ABC" means "#AABBCC", so does "#ABC0" mean "#AABBCC00"?   If that's legal, I'd want to support that too

**Comment by daattali** [comment]
I've made a few comments to the code

File: R/colourInput.R (hunk 3 above)
Comment (ddiez) [reply R/colourInput.R]: At least this is what I get with this code:

```
> plot(rnorm(100), col = "#FFF")
Error in plot.xy(xy, type, ...) : invalid RGB specification
```
Same using `"#FFFF"`. It works with `#FFFFFF` or `#FFFFFFFF`. I would have to check the R reference guide to be sure but it seems that it is not a valid specification. If it is not really legal, then you could simplify the code by removing the expansion at the end of the function.

File: R/colourInput.R (hunk 2 above)
Comment (ddiez) [reply R/colourInput.R:233]: Related to my comment below, this code doesn't work:

```
plot(rnorm(100), col = "FFFFFF")
Error in plot.xy(xy, type, ...) : invalid color name 'FFFFFF'
```
Same with alpha included. But maybe I'm missing the point and this is an R thing and you are talking about JS, and in JS it is allowed?

File: R/colourInput.R (hunk 1 above)
Comment (ddiez) [reply R/colourInput.R]: Yes, no problem. To be honest this is my first PR in which I have to make changes (this is my 3rd PR so far...). So, should I make the changes using the github editor in this PR's page? Or change my local copy and resubmit it? I guess the former but want to make sure...

File: R/colourInput.R (hunk 3 above)
Comment (daattali) [reply R/colourInput.R]: You're right, R doesn't support the [shorthand notation of hex colours](https://en.wikipedia.org/wiki/Web_colors#Shorthand_hexadecimal_form) (3 digits). But as someone who works a lot with colours (mostly on the web), I wanted to support that because I find it very convenient to be able to specify 3-digit colour codes. You'll often find in HTML code (or in CSS to be exact) that people use #0f0 instead of #00ff00. And the majority of the code for colourpicker is actually implemented in the javascript library I built for this, so that it could be used for HTML and not just for R.  

To answer my own question: it does look like [4-digit specification is indeed valid](https://drafts.csswg.org/css-color/#hex-notation)  (again, not in R, but in CSS, and I want to closely mimic web colours)

Does that make sense?

File: R/colourInput.R (hunk 2 above)
Comment (daattali) [reply R/colourInput.R:233]: Actually it's not allowed in CSS either :) This is something I wanted to allow just to "be useful with common errors". I've seen it very commonly that people forget to add the # in the beginning, so I specifically look for that and add it manually if need be.

File: R/colourInput.R (hunk 3 above)
Comment (ddiez) [reply R/colourInput.R]: I think it makes sense. After all the user will just see a web form and can input colors directly as hex codes, using 6/8 or 3/4 digits format. It shouldn't have to be limited by R's idiosyncrasy.

File: R/colourInput.R (hunk 2 above)
Comment (ddiez) [reply R/colourInput.R:233]: OK it makes sense, specially since end users may not know about those details.

Comment (ddiez) [reply R/colourInput.R:233]: Then I agree about putting the if statement after checking for `#`. Then, there is no need to check it in the `if` statement and there is need for two checks. One for 8-digit format (`nchar(x) == 9`) and another for 4-digit format (`nchar(x) == 5`).

File: R/colourInput.R (hunk 1 above)
Comment (daattali) [reply R/colourInput.R]: both are ok, whichever one is easier for you!

File: R/colourInput.R (hunk 2 above)
Comment (daattali) [reply R/colourInput.R:233]: yep that's right

File: R/colourInput.R (hunk 3 above)
Comment (daattali) [reply R/colourInput.R]: correct. You can actually type "abc" into the text input itself and it will automatically correct it to "#AABBCC"

**Comment by ddiez** [comment]
OK, I submitted the changes (tested them on the runExample() app and it seems to work). Finally did it from my fork and created a new pull request. Amazingly the system is smart enough to append it here! Hope didn't make any mistake...

**Comment by daattali** [comment]
Yup, GitHub is pretty awesome at making very smooth workflows. Thanks!
